<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('consat_calls', function (Blueprint $table) {
            $table->dropColumn('stop_point_id');
        });

        Schema::table('consat_call_details', function (Blueprint $table) {
            $table->dropColumn('event_type');
        });

        Schema::table('consat_passenger_count', function (Blueprint $table) {
            $table->dropPrimary(['date', 'id']);
            $table->dropColumn('id');
        });

        Schema::drop('consat_stops');
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::create('consat_stops', function (Blueprint $table) {
            $table->date('date')->comment('Date for when stop ID is valid');
            $table->unsignedBigInteger('id')->comment('Consat internal ID for this stop');
            $table->char('external_id', 64)->comment('NSR stop ID (or Regtopp for old sets)');
            $table->string('name', 128)->comment('Stop place name');
            $table->double('latitude')->comment('Latitude of stop place');
            $table->double('longitude')->comment('Longitude of stop place');

            $table->primary(['date', 'id']);
        });

        Schema::table('consat_calls', function (Blueprint $table) {
            $table->unsignedBigInteger('stop_point_id')->nullable()->after('sequence')->comment('References `consat_stops.id`');
        });

        Schema::table('consat_call_details', function (Blueprint $table) {
            $table->unsignedTinyInteger('event_type')->nullable()->after('call_id')->comment('Event type ID');
        });

        Schema::table('consat_passenger_count', function (Blueprint $table) {
            $table->unsignedBigInteger('id')->first()->comment('Journey ID generated by Consat');
        });
    }
};
