<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('consat_lines', function (Blueprint $table) {
            $table->date('date')->comment('Date of journey. Required join with other tables.');
            $table->unsignedBigInteger('id')->comment('Line ID generated by Consat');
            $table->char('line_id', 128)->comment('Line ID. References unavailable `line` table');
            $table->unsignedInteger('line')->comment('Line name.');

            $table->primary(['date', 'id']);
            $table->index(['date','line_id']);
        });

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('consat_lines');
    }
};
